### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by ssaguiar** [ShellAssistant/ShellAssistant#7]
Will the project be open source someday?
Thanks.

By the way, I am loving it.

**Comment by ShellAssistant** [comment]
At the moment I've no plans to release the code as open source, although that could always change in the future.

Thanks very much for your feedback. I'm so glad that you're enjoying using Shell Assistant!

**Comment by ShellAssistant** [comment]
Thanks very much for your interest in Shell Assistant. I think your question has been answered, so it should be ok to close this issue now. Please don't hesitate to get back in touch if you've any further questions or if I can help you in any other way!
